name: release
on:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types: 
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: katyo/publish-crates@v2
      with:
        registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
